common_settings:
  hosts:
    run_list: 'oci-infra-common::oci-bootstrap'
    keys: ['/opt/opschain/oci_new_key']
    use_flex: true
    cpu: 2
    memory: 16
    boot_volume_size_in_gbs: 75 
    native_instance_type: "VM.Standard3.Flex"
    operating_system: "Oracle Linux"
    operating_system_version: 9
    assign_public_ip: true
    configure_ocid_service: false
  storage:
    # storage_name: oracle
    size: 90
    mount_point: /oracle
  shared_storage:
    size: 50
    mount_point: /oracle/app/runtime
  domain_name: '.trial.limepoint.com'
  mount_target: 'mt-trial-obp-tst'
  sec_test_subnet: &sec_test_subnet 'sn-mp-trial-sec-tst'
  int_test_subnet: &int_test_subnet 'sn-mp-trial-int-tst'
  app_test_subnet: &app_test_subnet 'sn-mp-trial-tst'
  sec_test_network_security_groups: &sec_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-sec"]
  int_test_network_security_groups: &int_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-int"]
  app_test_network_security_groups: &app_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-app"]
assets:
  obpotd:
    subnet: sn-mp-trial-slb-tst
    run_list: 'oci-infra-common::oci-bootstrap'
    network_security_groups: ["nsg-mp-trial-slb-tst-apps", "nsg-mp-trial-tst-slb"]
    hosts:
      - name: cix4obpotd01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix4obpotd01-pca
            values: cix4obpotd01
        # chef_node_name: cix4obpotd01-pca
        # cpu: 2
        memory: 18 # you can override the global configs
        # primary_ip: 10.107.159.44
        # boot_volume_size: 75 
        storage:
        - storage_name: cix4obpotd01-oracle
      - name: cix4obpotd02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix4obpotd02-pca
            values: cix4obpotd02
        storage:
        - storage_name: cix4obpotd02-oracle
    shared_storage:
        - storage_name: cix4obpotd-runtime
          hosts:
            - cix4obpotd01
            - cix4obpotd02
          cluster_name: cix4obpotd
  obpoam:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix4obpoam01
        dns_entries: 
          - type: cname
            name: cix4obpoam01-pca
            values: cix4obpoam01
        storage:
        - storage_name: cix4obpoam01-oracle
      - name: cix4obpoam02
        dns_entries: 
          - type: cname
            name: cix4obpoam02-pca
            values: cix4obpoam02
        storage:
        - storage_name: cix4obpoam02-oracle
    shared_storage:
        - storage_name: cix4obpoam-runtime
          hosts:
            - cix4obpoam01
            - cix4obpoam02
          cluster_name: cix4obpoam
  obpoid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix4obpoid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix4obpoid01-pca
            values: cix4obpoid01
        storage:
        - storage_name: cix4obpoid01-oracle
      - name: cix4obpoid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix4obpoid02-pca
            values: cix4obpoid02
        storage:
        - storage_name: cix4obpoid02-oracle
    shared_storage:
        - storage_name: cix4obpoid-runtime
          hosts:
            - cix4obpoid01
            - cix4obpoid02
          cluster_name: cix4obpoid
  obpcid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix4obpcid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix4obpcid01-pca
            values: cix4obpcid01
        storage:
        - storage_name: cix4obpcid01-oracle
        - storage_name: cix4obpcid01-oraclenew
      - name: cix4obpcid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix4obpcid02-pca
            values: cix4obpcid02
        storage:
        - storage_name: cix4obpcid02-oracle
    shared_storage:
        - storage_name: cix4obpcid-runtime
          hosts:
            - cix4obpcid01
            - cix4obpcid02
          cluster_name: cix4obpcid
  obposb: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix4obposb01
        dns_entries: 
          - type: cname
            name: cix4obposb01-pca
            values: cix4obposb02
        storage:
        - storage_name: cix4obposb01-oracle
      - name: cix4obposb02
        dns_entries: 
          - type: cname
            name: cix4obposb02-pca
            values: cix4obposb02
        storage:
        - storage_name: cix4obposb02-oracle
    shared_storage:
        - storage_name: cix4obposb-runtime
          hosts:
            - cix4obposb01
            - cix4obposb02
          cluster_name: cix4obposb
  obpsoa: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix4obpsoa01
        dns_entries: 
          - type: cname
            name: cix4obpsoa01-pca
            values: cix4obpsoa01
        storage:
        - storage_name: cix4obpsoa01-oracle
      - name: cix4obpsoa02
        dns_entries: 
          - type: cname
            name: cix4obpsoa02-pca
            values: cix4obpsoa02
        storage:
        - storage_name: cix4obpsoa02-oracle
    shared_storage:
        - storage_name: cix4obpsoa-runtime
          hosts:
            - cix4obpsoa01
            - cix4obpsoa02
          cluster_name: cix4obpsoa
  obpdoc: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix4obpdoc01
        dns_entries: 
          - type: cname
            name: cix4obpdoc01-pca
            values: cix4obpdoc01
        storage:
        - storage_name: cix4obpdoc01-oracle
      - name: cix4obpdoc02
        dns_entries: 
          - type: cname
            name: cix4obpdoc02-pca
            values: cix4obpdoc02
        storage:
        - storage_name: cix4obpdoc02-oracle
    shared_storage:
        - storage_name: cix4obpdoc-runtime
          hosts:
            - cix4obpdoc01
            - cix4obpdoc02
          cluster_name: cix4obpdoc
  obpobh: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix4obpobh01
        dns_entries: 
          - type: cname
            name: cix4obpobh01-pca
            values: cix4obpobh01
        storage:
        - storage_name: cix4obpobh01-oracle
      - name: cix4obpobh02
        dns_entries: 
          - type: cname
            name: cix4obpobh02-pca
            values: cix4obpobh02
        storage:
        - storage_name: cix4obpobh02-oracle
    shared_storage:
        - storage_name: cix4obpobh-runtime
          hosts:
            - cix4obpobh01
            - cix4obpobh02
          cluster_name: cix4obpobh
  obpipm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix4obpipm01
        dns_entries: 
          - type: cname
            name: cix4obpipm01-pca
            values: cix4obpipm01
        storage:
        - storage_name: cix4obpipm01-oracle
      - name: cix4obpipm02
        dns_entries: 
          - type: cname
            name: cix4obpipm02-pca
            values: cix4obpipm02
        storage:
        - storage_name: cix4obpipm02-oracle
    shared_storage:
        - storage_name: cix4obpipm-runtime
          hosts:
            - cix4obpipm01
            - cix4obpipm02
          cluster_name: cix4obpipm
  obpurm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix4obpurm01
        dns_entries: 
          - type: cname
            name: cix4obpurm01-pca
            values: cix4obpurm01
        storage:
        - storage_name: cix4obpurm01-oracle
      - name: cix4obpurm02
        dns_entries: 
          - type: cname
            name: cix4obpurm02-pca
            values: cix4obpurm02
        storage:
        - storage_name: cix4obpurm02-oracle
    shared_storage:
        - storage_name: cix4obpurm-runtime
          hosts:
            - cix4obpurm01
            - cix4obpurm02
          cluster_name: cix4obpurm
  obpobu: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix4obpobu01
        dns_entries: 
          - type: cname
            name: cix4obpobu01-pca
            values: cix4obpobu01
        storage:
        - storage_name: cix4obpobu01-oracle
      - name: cix4obpobu02
        dns_entries: 
          - type: cname
            name: cix4obpobu02-pca
            values: cix4obpobu02
        storage:
        - storage_name: cix4obpobu02-oracle
    shared_storage:
        - storage_name: cix4obpobu-runtime
          hosts:
            - cix4obpobu01
            - cix4obpobu02
          cluster_name: cix4obpobu
  obpodi: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix4obpodi01
        dns_entries: 
          - type: cname
            name: cix4obpodi01-pca
            values: cix4obpodi01
        storage:
        - storage_name: cix4obpodi01-oracle
      - name: cix4obpodi02
        dns_entries: 
          - type: cname
            name: cix4obpodi02-pca
            values: cix4obpodi02
        storage:
        - storage_name: cix4obpodi02-oracle
    shared_storage:
        - storage_name: cix4obpodi-runtime
          hosts:
            - cix4obpodi01
            - cix4obpodi02
          cluster_name: cix4obpodi