common_settings:
  hosts:
    run_list: 'oci-infra-common::oci-bootstrap'
    keys: ['/opt/opschain/oci_new_key']
    use_flex: true
    cpu: 2
    memory: 16
    boot_volume_size_in_gbs: 75 
    native_instance_type: "VM.Standard3.Flex"
    operating_system: "Oracle Linux"
    operating_system_version: 9
    assign_public_ip: true
    configure_ocid_service: false
  storage:
    # storage_name: oracle
    size: 90
    mount_point: /oracle
  shared_storage:
    size: 50
    mount_point: /oracle/app/runtime
  domain_name: '.trial.limepoint.com'
  mount_target: 'mt-trial-obp-tst'
  sec_test_subnet: &sec_test_subnet 'sn-mp-trial-sec-tst'
  int_test_subnet: &int_test_subnet 'sn-mp-trial-int-tst'
  app_test_subnet: &app_test_subnet 'sn-mp-trial-tst'
  sec_test_network_security_groups: &sec_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-sec"]
  int_test_network_security_groups: &int_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-int"]
  app_test_network_security_groups: &app_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-app"]
assets:
  obpotd:
    subnet: sn-mp-trial-slb-tst
    run_list: 'oci-infra-common::oci-bootstrap'
    network_security_groups: ["nsg-mp-trial-slb-tst-apps", "nsg-mp-trial-tst-slb"]
    hosts:
      - name: cix6obpotd01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix6obpotd01-pca
            values: cix6obpotd01
        # chef_node_name: cix6obpotd01-pca
        # cpu: 2
        memory: 18 # you can override the global configs
        # primary_ip: 10.107.159.44
        # boot_volume_size: 75 
        storage:
        - storage_name: cix6obpotd01-oracle
      - name: cix6obpotd02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix6obpotd02-pca
            values: cix6obpotd02
        storage:
        - storage_name: cix6obpotd02-oracle
    shared_storage:
        - storage_name: cix6obpotd-runtime
          hosts:
            - cix6obpotd01
            - cix6obpotd02
          cluster_name: cix6obpotd
  obpoam:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix6obpoam01
        dns_entries: 
          - type: cname
            name: cix6obpoam01-pca
            values: cix6obpoam01
        storage:
        - storage_name: cix6obpoam01-oracle
      - name: cix6obpoam02
        dns_entries: 
          - type: cname
            name: cix6obpoam02-pca
            values: cix6obpoam02
        storage:
        - storage_name: cix6obpoam02-oracle
    shared_storage:
        - storage_name: cix6obpoam-runtime
          hosts:
            - cix6obpoam01
            - cix6obpoam02
          cluster_name: cix6obpoam
  obpoid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix6obpoid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix6obpoid01-pca
            values: cix6obpoid01
        storage:
        - storage_name: cix6obpoid01-oracle
      - name: cix6obpoid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix6obpoid02-pca
            values: cix6obpoid02
        storage:
        - storage_name: cix6obpoid02-oracle
    shared_storage:
        - storage_name: cix6obpoid-runtime
          hosts:
            - cix6obpoid01
            - cix6obpoid02
          cluster_name: cix6obpoid
  obpcid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix6obpcid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix6obpcid01-pca
            values: cix6obpcid01
        storage:
        - storage_name: cix6obpcid01-oracle
        - storage_name: cix6obpcid01-oraclenew
      - name: cix6obpcid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix6obpcid02-pca
            values: cix6obpcid02
        storage:
        - storage_name: cix6obpcid02-oracle
    shared_storage:
        - storage_name: cix6obpcid-runtime
          hosts:
            - cix6obpcid01
            - cix6obpcid02
          cluster_name: cix6obpcid
  obposb: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix6obposb01
        dns_entries: 
          - type: cname
            name: cix6obposb01-pca
            values: cix6obposb02
        storage:
        - storage_name: cix6obposb01-oracle
      - name: cix6obposb02
        dns_entries: 
          - type: cname
            name: cix6obposb02-pca
            values: cix6obposb02
        storage:
        - storage_name: cix6obposb02-oracle
    shared_storage:
        - storage_name: cix6obposb-runtime
          hosts:
            - cix6obposb01
            - cix6obposb02
          cluster_name: cix6obposb
  obpsoa: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix6obpsoa01
        dns_entries: 
          - type: cname
            name: cix6obpsoa01-pca
            values: cix6obpsoa01
        storage:
        - storage_name: cix6obpsoa01-oracle
      - name: cix6obpsoa02
        dns_entries: 
          - type: cname
            name: cix6obpsoa02-pca
            values: cix6obpsoa02
        storage:
        - storage_name: cix6obpsoa02-oracle
    shared_storage:
        - storage_name: cix6obpsoa-runtime
          hosts:
            - cix6obpsoa01
            - cix6obpsoa02
          cluster_name: cix6obpsoa
  obpdoc: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix6obpdoc01
        dns_entries: 
          - type: cname
            name: cix6obpdoc01-pca
            values: cix6obpdoc01
        storage:
        - storage_name: cix6obpdoc01-oracle
      - name: cix6obpdoc02
        dns_entries: 
          - type: cname
            name: cix6obpdoc02-pca
            values: cix6obpdoc02
        storage:
        - storage_name: cix6obpdoc02-oracle
    shared_storage:
        - storage_name: cix6obpdoc-runtime
          hosts:
            - cix6obpdoc01
            - cix6obpdoc02
          cluster_name: cix6obpdoc
  obpobh: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix6obpobh01
        dns_entries: 
          - type: cname
            name: cix6obpobh01-pca
            values: cix6obpobh01
        storage:
        - storage_name: cix6obpobh01-oracle
      - name: cix6obpobh02
        dns_entries: 
          - type: cname
            name: cix6obpobh02-pca
            values: cix6obpobh02
        storage:
        - storage_name: cix6obpobh02-oracle
    shared_storage:
        - storage_name: cix6obpobh-runtime
          hosts:
            - cix6obpobh01
            - cix6obpobh02
          cluster_name: cix6obpobh
  obpipm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix6obpipm01
        dns_entries: 
          - type: cname
            name: cix6obpipm01-pca
            values: cix6obpipm01
        storage:
        - storage_name: cix6obpipm01-oracle
      - name: cix6obpipm02
        dns_entries: 
          - type: cname
            name: cix6obpipm02-pca
            values: cix6obpipm02
        storage:
        - storage_name: cix6obpipm02-oracle
    shared_storage:
        - storage_name: cix6obpipm-runtime
          hosts:
            - cix6obpipm01
            - cix6obpipm02
          cluster_name: cix6obpipm
  obpurm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix6obpurm01
        dns_entries: 
          - type: cname
            name: cix6obpurm01-pca
            values: cix6obpurm01
        storage:
        - storage_name: cix6obpurm01-oracle
      - name: cix6obpurm02
        dns_entries: 
          - type: cname
            name: cix6obpurm02-pca
            values: cix6obpurm02
        storage:
        - storage_name: cix6obpurm02-oracle
    shared_storage:
        - storage_name: cix6obpurm-runtime
          hosts:
            - cix6obpurm01
            - cix6obpurm02
          cluster_name: cix6obpurm
  obpobu: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix6obpobu01
        dns_entries: 
          - type: cname
            name: cix6obpobu01-pca
            values: cix6obpobu01
        storage:
        - storage_name: cix6obpobu01-oracle
      - name: cix6obpobu02
        dns_entries: 
          - type: cname
            name: cix6obpobu02-pca
            values: cix6obpobu02
        storage:
        - storage_name: cix6obpobu02-oracle
    shared_storage:
        - storage_name: cix6obpobu-runtime
          hosts:
            - cix6obpobu01
            - cix6obpobu02
          cluster_name: cix6obpobu
  obpodi: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix6obpodi01
        dns_entries: 
          - type: cname
            name: cix6obpodi01-pca
            values: cix6obpodi01
        storage:
        - storage_name: cix6obpodi01-oracle
      - name: cix6obpodi02
        dns_entries: 
          - type: cname
            name: cix6obpodi02-pca
            values: cix6obpodi02
        storage:
        - storage_name: cix6obpodi02-oracle
    shared_storage:
        - storage_name: cix6obpodi-runtime
          hosts:
            - cix6obpodi01
            - cix6obpodi02
          cluster_name: cix6obpodi