common_settings:
  hosts:
    run_list: 'oci-infra-common::oci-bootstrap'
    keys: ['/opt/opschain/oci_new_key']
    use_flex: true
    cpu: 2
    memory: 16
    boot_volume_size_in_gbs: 75 
    native_instance_type: "VM.Standard3.Flex"
    operating_system: "Oracle Linux"
    operating_system_version: 9
    assign_public_ip: true
    configure_ocid_service: false
  storage:
    # storage_name: oracle
    size: 90
    mount_point: /oracle
  shared_storage:
    size: 50
    mount_point: /oracle/app/runtime
  domain_name: '.trial.limepoint.com'
  mount_target: 'mt-trial-obp-tst'
  sec_test_subnet: &sec_test_subnet 'sn-mp-trial-sec-tst'
  int_test_subnet: &int_test_subnet 'sn-mp-trial-int-tst'
  app_test_subnet: &app_test_subnet 'sn-mp-trial-tst'
  sec_test_network_security_groups: &sec_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-sec"]
  int_test_network_security_groups: &int_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-int"]
  app_test_network_security_groups: &app_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-app"]
assets:
  obpotd:
    subnet: sn-mp-trial-slb-tst
    run_list: 'oci-infra-common::oci-bootstrap'
    network_security_groups: ["nsg-mp-trial-slb-tst-apps", "nsg-mp-trial-tst-slb"]
    hosts:
      - name: cix7obpotd01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix7obpotd01-pca
            values: cix7obpotd01
        # chef_node_name: cix7obpotd01-pca
        # cpu: 2
        memory: 18 # you can override the global configs
        # primary_ip: 10.107.159.44
        # boot_volume_size: 75 
        storage:
        - storage_name: cix7obpotd01-oracle
      - name: cix7obpotd02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix7obpotd02-pca
            values: cix7obpotd02
        storage:
        - storage_name: cix7obpotd02-oracle
    shared_storage:
        - storage_name: cix7obpotd-runtime
          hosts:
            - cix7obpotd01
            - cix7obpotd02
          cluster_name: cix7obpotd
  obpoam:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix7obpoam01
        dns_entries: 
          - type: cname
            name: cix7obpoam01-pca
            values: cix7obpoam01
        storage:
        - storage_name: cix7obpoam01-oracle
      - name: cix7obpoam02
        dns_entries: 
          - type: cname
            name: cix7obpoam02-pca
            values: cix7obpoam02
        storage:
        - storage_name: cix7obpoam02-oracle
    shared_storage:
        - storage_name: cix7obpoam-runtime
          hosts:
            - cix7obpoam01
            - cix7obpoam02
          cluster_name: cix7obpoam
  obpoid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix7obpoid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix7obpoid01-pca
            values: cix7obpoid01
        storage:
        - storage_name: cix7obpoid01-oracle
      - name: cix7obpoid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix7obpoid02-pca
            values: cix7obpoid02
        storage:
        - storage_name: cix7obpoid02-oracle
    shared_storage:
        - storage_name: cix7obpoid-runtime
          hosts:
            - cix7obpoid01
            - cix7obpoid02
          cluster_name: cix7obpoid
  obpcid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix7obpcid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix7obpcid01-pca
            values: cix7obpcid01
        storage:
        - storage_name: cix7obpcid01-oracle
        - storage_name: cix7obpcid01-oraclenew
      - name: cix7obpcid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix7obpcid02-pca
            values: cix7obpcid02
        storage:
        - storage_name: cix7obpcid02-oracle
    shared_storage:
        - storage_name: cix7obpcid-runtime
          hosts:
            - cix7obpcid01
            - cix7obpcid02
          cluster_name: cix7obpcid
  obposb: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix7obposb01
        dns_entries: 
          - type: cname
            name: cix7obposb01-pca
            values: cix7obposb02
        storage:
        - storage_name: cix7obposb01-oracle
      - name: cix7obposb02
        dns_entries: 
          - type: cname
            name: cix7obposb02-pca
            values: cix7obposb02
        storage:
        - storage_name: cix7obposb02-oracle
    shared_storage:
        - storage_name: cix7obposb-runtime
          hosts:
            - cix7obposb01
            - cix7obposb02
          cluster_name: cix7obposb
  obpsoa: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix7obpsoa01
        dns_entries: 
          - type: cname
            name: cix7obpsoa01-pca
            values: cix7obpsoa01
        storage:
        - storage_name: cix7obpsoa01-oracle
      - name: cix7obpsoa02
        dns_entries: 
          - type: cname
            name: cix7obpsoa02-pca
            values: cix7obpsoa02
        storage:
        - storage_name: cix7obpsoa02-oracle
    shared_storage:
        - storage_name: cix7obpsoa-runtime
          hosts:
            - cix7obpsoa01
            - cix7obpsoa02
          cluster_name: cix7obpsoa
  obpdoc: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix7obpdoc01
        dns_entries: 
          - type: cname
            name: cix7obpdoc01-pca
            values: cix7obpdoc01
        storage:
        - storage_name: cix7obpdoc01-oracle
      - name: cix7obpdoc02
        dns_entries: 
          - type: cname
            name: cix7obpdoc02-pca
            values: cix7obpdoc02
        storage:
        - storage_name: cix7obpdoc02-oracle
    shared_storage:
        - storage_name: cix7obpdoc-runtime
          hosts:
            - cix7obpdoc01
            - cix7obpdoc02
          cluster_name: cix7obpdoc
  obpobh: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix7obpobh01
        dns_entries: 
          - type: cname
            name: cix7obpobh01-pca
            values: cix7obpobh01
        storage:
        - storage_name: cix7obpobh01-oracle
      - name: cix7obpobh02
        dns_entries: 
          - type: cname
            name: cix7obpobh02-pca
            values: cix7obpobh02
        storage:
        - storage_name: cix7obpobh02-oracle
    shared_storage:
        - storage_name: cix7obpobh-runtime
          hosts:
            - cix7obpobh01
            - cix7obpobh02
          cluster_name: cix7obpobh
  obpipm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix7obpipm01
        dns_entries: 
          - type: cname
            name: cix7obpipm01-pca
            values: cix7obpipm01
        storage:
        - storage_name: cix7obpipm01-oracle
      - name: cix7obpipm02
        dns_entries: 
          - type: cname
            name: cix7obpipm02-pca
            values: cix7obpipm02
        storage:
        - storage_name: cix7obpipm02-oracle
    shared_storage:
        - storage_name: cix7obpipm-runtime
          hosts:
            - cix7obpipm01
            - cix7obpipm02
          cluster_name: cix7obpipm
  obpurm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix7obpurm01
        dns_entries: 
          - type: cname
            name: cix7obpurm01-pca
            values: cix7obpurm01
        storage:
        - storage_name: cix7obpurm01-oracle
      - name: cix7obpurm02
        dns_entries: 
          - type: cname
            name: cix7obpurm02-pca
            values: cix7obpurm02
        storage:
        - storage_name: cix7obpurm02-oracle
    shared_storage:
        - storage_name: cix7obpurm-runtime
          hosts:
            - cix7obpurm01
            - cix7obpurm02
          cluster_name: cix7obpurm
  obpobu: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix7obpobu01
        dns_entries: 
          - type: cname
            name: cix7obpobu01-pca
            values: cix7obpobu01
        storage:
        - storage_name: cix7obpobu01-oracle
      - name: cix7obpobu02
        dns_entries: 
          - type: cname
            name: cix7obpobu02-pca
            values: cix7obpobu02
        storage:
        - storage_name: cix7obpobu02-oracle
    shared_storage:
        - storage_name: cix7obpobu-runtime
          hosts:
            - cix7obpobu01
            - cix7obpobu02
          cluster_name: cix7obpobu
  obpodi: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix7obpodi01
        dns_entries: 
          - type: cname
            name: cix7obpodi01-pca
            values: cix7obpodi01
        storage:
        - storage_name: cix7obpodi01-oracle
      - name: cix7obpodi02
        dns_entries: 
          - type: cname
            name: cix7obpodi02-pca
            values: cix7obpodi02
        storage:
        - storage_name: cix7obpodi02-oracle
    shared_storage:
        - storage_name: cix7obpodi-runtime
          hosts:
            - cix7obpodi01
            - cix7obpodi02
          cluster_name: cix7obpodi