common_settings:
  hosts:
    run_list: 'oci-infra-common::oci-bootstrap'
    keys: ['/opt/opschain/oci_new_key']
    use_flex: true
    cpu: 2
    memory: 16
    boot_volume_size_in_gbs: 75 
    native_instance_type: "VM.Standard3.Flex"
    operating_system: "Oracle Linux"
    operating_system_version: 9
    assign_public_ip: true
    configure_ocid_service: false
  storage:
    # storage_name: oracle
    size: 90
    mount_point: /oracle
  shared_storage:
    size: 50
    mount_point: /oracle/app/runtime
  domain_name: '.trial.limepoint.com'
  mount_target: 'mt-trial-obp-tst'
  sec_test_subnet: &sec_test_subnet 'sn-mp-trial-sec-tst'
  int_test_subnet: &int_test_subnet 'sn-mp-trial-int-tst'
  app_test_subnet: &app_test_subnet 'sn-mp-trial-tst'
  sec_test_network_security_groups: &sec_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-sec"]
  int_test_network_security_groups: &int_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-int"]
  app_test_network_security_groups: &app_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-app"]
assets:
  obpotd:
    subnet: sn-mp-trial-slb-tst
    run_list: 'oci-infra-common::oci-bootstrap'
    network_security_groups: ["nsg-mp-trial-slb-tst-apps", "nsg-mp-trial-tst-slb"]
    hosts:
      - name: cix5obpotd01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix5obpotd01-pca
            values: cix5obpotd01
        # chef_node_name: cix5obpotd01-pca
        # cpu: 2
        memory: 18 # you can override the global configs
        # primary_ip: 10.107.159.44
        # boot_volume_size: 75 
        storage:
        - storage_name: cix5obpotd01-oracle
      - name: cix5obpotd02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix5obpotd02-pca
            values: cix5obpotd02
        storage:
        - storage_name: cix5obpotd02-oracle
    shared_storage:
        - storage_name: cix5obpotd-runtime
          hosts:
            - cix5obpotd01
            - cix5obpotd02
          cluster_name: cix5obpotd
  obpoam:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix5obpoam01
        dns_entries: 
          - type: cname
            name: cix5obpoam01-pca
            values: cix5obpoam01
        storage:
        - storage_name: cix5obpoam01-oracle
      - name: cix5obpoam02
        dns_entries: 
          - type: cname
            name: cix5obpoam02-pca
            values: cix5obpoam02
        storage:
        - storage_name: cix5obpoam02-oracle
    shared_storage:
        - storage_name: cix5obpoam-runtime
          hosts:
            - cix5obpoam01
            - cix5obpoam02
          cluster_name: cix5obpoam
  obpoid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix5obpoid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix5obpoid01-pca
            values: cix5obpoid01
        storage:
        - storage_name: cix5obpoid01-oracle
      - name: cix5obpoid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix5obpoid02-pca
            values: cix5obpoid02
        storage:
        - storage_name: cix5obpoid02-oracle
    shared_storage:
        - storage_name: cix5obpoid-runtime
          hosts:
            - cix5obpoid01
            - cix5obpoid02
          cluster_name: cix5obpoid
  obpcid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix5obpcid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix5obpcid01-pca
            values: cix5obpcid01
        storage:
        - storage_name: cix5obpcid01-oracle
        - storage_name: cix5obpcid01-oraclenew
      - name: cix5obpcid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix5obpcid02-pca
            values: cix5obpcid02
        storage:
        - storage_name: cix5obpcid02-oracle
    shared_storage:
        - storage_name: cix5obpcid-runtime
          hosts:
            - cix5obpcid01
            - cix5obpcid02
          cluster_name: cix5obpcid
  obposb: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix5obposb01
        dns_entries: 
          - type: cname
            name: cix5obposb01-pca
            values: cix5obposb02
        storage:
        - storage_name: cix5obposb01-oracle
      - name: cix5obposb02
        dns_entries: 
          - type: cname
            name: cix5obposb02-pca
            values: cix5obposb02
        storage:
        - storage_name: cix5obposb02-oracle
    shared_storage:
        - storage_name: cix5obposb-runtime
          hosts:
            - cix5obposb01
            - cix5obposb02
          cluster_name: cix5obposb
  obpsoa: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix5obpsoa01
        dns_entries: 
          - type: cname
            name: cix5obpsoa01-pca
            values: cix5obpsoa01
        storage:
        - storage_name: cix5obpsoa01-oracle
      - name: cix5obpsoa02
        dns_entries: 
          - type: cname
            name: cix5obpsoa02-pca
            values: cix5obpsoa02
        storage:
        - storage_name: cix5obpsoa02-oracle
    shared_storage:
        - storage_name: cix5obpsoa-runtime
          hosts:
            - cix5obpsoa01
            - cix5obpsoa02
          cluster_name: cix5obpsoa
  obpdoc: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix5obpdoc01
        dns_entries: 
          - type: cname
            name: cix5obpdoc01-pca
            values: cix5obpdoc01
        storage:
        - storage_name: cix5obpdoc01-oracle
      - name: cix5obpdoc02
        dns_entries: 
          - type: cname
            name: cix5obpdoc02-pca
            values: cix5obpdoc02
        storage:
        - storage_name: cix5obpdoc02-oracle
    shared_storage:
        - storage_name: cix5obpdoc-runtime
          hosts:
            - cix5obpdoc01
            - cix5obpdoc02
          cluster_name: cix5obpdoc
  obpobh: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix5obpobh01
        dns_entries: 
          - type: cname
            name: cix5obpobh01-pca
            values: cix5obpobh01
        storage:
        - storage_name: cix5obpobh01-oracle
      - name: cix5obpobh02
        dns_entries: 
          - type: cname
            name: cix5obpobh02-pca
            values: cix5obpobh02
        storage:
        - storage_name: cix5obpobh02-oracle
    shared_storage:
        - storage_name: cix5obpobh-runtime
          hosts:
            - cix5obpobh01
            - cix5obpobh02
          cluster_name: cix5obpobh
  obpipm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix5obpipm01
        dns_entries: 
          - type: cname
            name: cix5obpipm01-pca
            values: cix5obpipm01
        storage:
        - storage_name: cix5obpipm01-oracle
      - name: cix5obpipm02
        dns_entries: 
          - type: cname
            name: cix5obpipm02-pca
            values: cix5obpipm02
        storage:
        - storage_name: cix5obpipm02-oracle
    shared_storage:
        - storage_name: cix5obpipm-runtime
          hosts:
            - cix5obpipm01
            - cix5obpipm02
          cluster_name: cix5obpipm
  obpurm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix5obpurm01
        dns_entries: 
          - type: cname
            name: cix5obpurm01-pca
            values: cix5obpurm01
        storage:
        - storage_name: cix5obpurm01-oracle
      - name: cix5obpurm02
        dns_entries: 
          - type: cname
            name: cix5obpurm02-pca
            values: cix5obpurm02
        storage:
        - storage_name: cix5obpurm02-oracle
    shared_storage:
        - storage_name: cix5obpurm-runtime
          hosts:
            - cix5obpurm01
            - cix5obpurm02
          cluster_name: cix5obpurm
  obpobu: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix5obpobu01
        dns_entries: 
          - type: cname
            name: cix5obpobu01-pca
            values: cix5obpobu01
        storage:
        - storage_name: cix5obpobu01-oracle
      - name: cix5obpobu02
        dns_entries: 
          - type: cname
            name: cix5obpobu02-pca
            values: cix5obpobu02
        storage:
        - storage_name: cix5obpobu02-oracle
    shared_storage:
        - storage_name: cix5obpobu-runtime
          hosts:
            - cix5obpobu01
            - cix5obpobu02
          cluster_name: cix5obpobu
  obpodi: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix5obpodi01
        dns_entries: 
          - type: cname
            name: cix5obpodi01-pca
            values: cix5obpodi01
        storage:
        - storage_name: cix5obpodi01-oracle
      - name: cix5obpodi02
        dns_entries: 
          - type: cname
            name: cix5obpodi02-pca
            values: cix5obpodi02
        storage:
        - storage_name: cix5obpodi02-oracle
    shared_storage:
        - storage_name: cix5obpodi-runtime
          hosts:
            - cix5obpodi01
            - cix5obpodi02
          cluster_name: cix5obpodi