common_settings:
  hosts:
    run_list: 'oci-infra-common::oci-bootstrap'
    keys: ['/opt/opschain/oci_new_key']
    use_flex: true
    cpu: 2
    memory: 16
    boot_volume_size_in_gbs: 75 
    native_instance_type: "VM.Standard3.Flex"
    operating_system: "Oracle Linux"
    operating_system_version: 9
    assign_public_ip: true
    configure_ocid_service: false
  storage:
    # storage_name: oracle
    size: 90
    mount_point: /oracle
  shared_storage:
    size: 50
    mount_point: /oracle/app/runtime
  domain_name: '.trial.limepoint.com'
  mount_target: 'mt-trial-obp-tst'
  sec_test_subnet: &sec_test_subnet 'sn-mp-trial-sec-tst'
  int_test_subnet: &int_test_subnet 'sn-mp-trial-int-tst'
  app_test_subnet: &app_test_subnet 'sn-mp-trial-tst'
  sec_test_network_security_groups: &sec_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-sec"]
  int_test_network_security_groups: &int_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-int"]
  app_test_network_security_groups: &app_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-app"]
assets:
  obpotd:
    subnet: sn-mp-trial-slb-tst
    run_list: 'oci-infra-common::oci-bootstrap'
    network_security_groups: ["nsg-mp-trial-slb-tst-apps", "nsg-mp-trial-tst-slb"]
    hosts:
      - name: cix10obpotd01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix10obpotd01-pca
            values: cix10obpotd01
        # chef_node_name: cix10obpotd01-pca
        # cpu: 2
        memory: 18 # you can override the global configs
        # primary_ip: 10.107.159.44
        # boot_volume_size: 75 
        storage:
        - storage_name: cix10obpotd01-oracle
      - name: cix10obpotd02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix10obpotd02-pca
            values: cix10obpotd02
        storage:
        - storage_name: cix10obpotd02-oracle
    shared_storage:
        - storage_name: cix10obpotd-runtime
          hosts:
            - cix10obpotd01
            - cix10obpotd02
          cluster_name: cix10obpotd
  obpoam:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix10obpoam01
        dns_entries: 
          - type: cname
            name: cix10obpoam01-pca
            values: cix10obpoam01
        storage:
        - storage_name: cix10obpoam01-oracle
      - name: cix10obpoam02
        dns_entries: 
          - type: cname
            name: cix10obpoam02-pca
            values: cix10obpoam02
        storage:
        - storage_name: cix10obpoam02-oracle
    shared_storage:
        - storage_name: cix10obpoam-runtime
          hosts:
            - cix10obpoam01
            - cix10obpoam02
          cluster_name: cix10obpoam
  obpoid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix10obpoid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix10obpoid01-pca
            values: cix10obpoid01
        storage:
        - storage_name: cix10obpoid01-oracle
      - name: cix10obpoid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix10obpoid02-pca
            values: cix10obpoid02
        storage:
        - storage_name: cix10obpoid02-oracle
    shared_storage:
        - storage_name: cix10obpoid-runtime
          hosts:
            - cix10obpoid01
            - cix10obpoid02
          cluster_name: cix10obpoid
  obpcid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix10obpcid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix10obpcid01-pca
            values: cix10obpcid01
        storage:
        - storage_name: cix10obpcid01-oracle
        - storage_name: cix10obpcid01-oraclenew
      - name: cix10obpcid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix10obpcid02-pca
            values: cix10obpcid02
        storage:
        - storage_name: cix10obpcid02-oracle
    shared_storage:
        - storage_name: cix10obpcid-runtime
          hosts:
            - cix10obpcid01
            - cix10obpcid02
          cluster_name: cix10obpcid
  obposb: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix10obposb01
        dns_entries: 
          - type: cname
            name: cix10obposb01-pca
            values: cix10obposb02
        storage:
        - storage_name: cix10obposb01-oracle
      - name: cix10obposb02
        dns_entries: 
          - type: cname
            name: cix10obposb02-pca
            values: cix10obposb02
        storage:
        - storage_name: cix10obposb02-oracle
    shared_storage:
        - storage_name: cix10obposb-runtime
          hosts:
            - cix10obposb01
            - cix10obposb02
          cluster_name: cix10obposb
  obpsoa: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix10obpsoa01
        dns_entries: 
          - type: cname
            name: cix10obpsoa01-pca
            values: cix10obpsoa01
        storage:
        - storage_name: cix10obpsoa01-oracle
      - name: cix10obpsoa02
        dns_entries: 
          - type: cname
            name: cix10obpsoa02-pca
            values: cix10obpsoa02
        storage:
        - storage_name: cix10obpsoa02-oracle
    shared_storage:
        - storage_name: cix10obpsoa-runtime
          hosts:
            - cix10obpsoa01
            - cix10obpsoa02
          cluster_name: cix10obpsoa
  obpdoc: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix10obpdoc01
        dns_entries: 
          - type: cname
            name: cix10obpdoc01-pca
            values: cix10obpdoc01
        storage:
        - storage_name: cix10obpdoc01-oracle
      - name: cix10obpdoc02
        dns_entries: 
          - type: cname
            name: cix10obpdoc02-pca
            values: cix10obpdoc02
        storage:
        - storage_name: cix10obpdoc02-oracle
    shared_storage:
        - storage_name: cix10obpdoc-runtime
          hosts:
            - cix10obpdoc01
            - cix10obpdoc02
          cluster_name: cix10obpdoc
  obpobh: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix10obpobh01
        dns_entries: 
          - type: cname
            name: cix10obpobh01-pca
            values: cix10obpobh01
        storage:
        - storage_name: cix10obpobh01-oracle
      - name: cix10obpobh02
        dns_entries: 
          - type: cname
            name: cix10obpobh02-pca
            values: cix10obpobh02
        storage:
        - storage_name: cix10obpobh02-oracle
    shared_storage:
        - storage_name: cix10obpobh-runtime
          hosts:
            - cix10obpobh01
            - cix10obpobh02
          cluster_name: cix10obpobh
  obpipm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix10obpipm01
        dns_entries: 
          - type: cname
            name: cix10obpipm01-pca
            values: cix10obpipm01
        storage:
        - storage_name: cix10obpipm01-oracle
      - name: cix10obpipm02
        dns_entries: 
          - type: cname
            name: cix10obpipm02-pca
            values: cix10obpipm02
        storage:
        - storage_name: cix10obpipm02-oracle
    shared_storage:
        - storage_name: cix10obpipm-runtime
          hosts:
            - cix10obpipm01
            - cix10obpipm02
          cluster_name: cix10obpipm
  obpurm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix10obpurm01
        dns_entries: 
          - type: cname
            name: cix10obpurm01-pca
            values: cix10obpurm01
        storage:
        - storage_name: cix10obpurm01-oracle
      - name: cix10obpurm02
        dns_entries: 
          - type: cname
            name: cix10obpurm02-pca
            values: cix10obpurm02
        storage:
        - storage_name: cix10obpurm02-oracle
    shared_storage:
        - storage_name: cix10obpurm-runtime
          hosts:
            - cix10obpurm01
            - cix10obpurm02
          cluster_name: cix10obpurm
  obpobu: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix10obpobu01
        dns_entries: 
          - type: cname
            name: cix10obpobu01-pca
            values: cix10obpobu01
        storage:
        - storage_name: cix10obpobu01-oracle
      - name: cix10obpobu02
        dns_entries: 
          - type: cname
            name: cix10obpobu02-pca
            values: cix10obpobu02
        storage:
        - storage_name: cix10obpobu02-oracle
    shared_storage:
        - storage_name: cix10obpobu-runtime
          hosts:
            - cix10obpobu01
            - cix10obpobu02
          cluster_name: cix10obpobu
  obpodi: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix10obpodi01
        dns_entries: 
          - type: cname
            name: cix10obpodi01-pca
            values: cix10obpodi01
        storage:
        - storage_name: cix10obpodi01-oracle
      - name: cix10obpodi02
        dns_entries: 
          - type: cname
            name: cix10obpodi02-pca
            values: cix10obpodi02
        storage:
        - storage_name: cix10obpodi02-oracle
    shared_storage:
        - storage_name: cix10obpodi-runtime
          hosts:
            - cix10obpodi01
            - cix10obpodi02
          cluster_name: cix10obpodi