common_settings:
  hosts:
    run_list: 'oci-infra-common::oci-bootstrap'
    keys: ['/opt/opschain/oci_new_key']
    use_flex: true
    cpu: 2
    memory: 16
    boot_volume_size_in_gbs: 75 
    native_instance_type: "VM.Standard3.Flex"
    operating_system: "Oracle Linux"
    operating_system_version: 9
    assign_public_ip: true
    configure_ocid_service: false
  storage:
    storage_name: oracle
    size: 90
    mount_point: /oracle
  shared_storage:
    size: 50
    mount_point: /oracle/app/runtime
  domain_name: '.trial.limepoint.com'
  mount_target: 'mt-trial-obp-tst'
  sec_test_subnet: &sec_test_subnet 'sn-mp-trial-sec-tst'
  int_test_subnet: &int_test_subnet 'sn-mp-trial-int-tst'
  app_test_subnet: &app_test_subnet 'sn-mp-trial-tst'
  sec_test_network_security_groups: &sec_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-sec"]
  int_test_network_security_groups: &int_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-int"]
  app_test_network_security_groups: &app_test_network_security_groups ["nsg-mp-trial-tst-common-ops", "nsg-mp-trial-tst-common-apps", "nsg-mp-trial-tst-app"]
assets:
  obpotd:
    subnet: sn-mp-trial-slb-tst
    run_list: 'oci-infra-common::oci-bootstrap'
    network_security_groups: ["nsg-mp-trial-slb-tst-apps", "nsg-mp-trial-tst-slb"]
    hosts:
      - name: cix1obpotd01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix1obpotd01-pca
            values: cix1obpotd01
        # chef_node_name: cix1obpotd01-pca
        # cpu: 2
        memory: 18 # you can override the global configs
        # primary_ip: 10.107.159.44
        # boot_volume_size: 75 
        storage:
        - storage_name: cix1obpotd01-oracle
      - name: cix1obpotd02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix1obpotd02-pca
            values: cix1obpotd02
        storage:
        - storage_name: cix1obpotd02-oracle
    shared_storage:
        - storage_name: cix1obpotd-runtime
          hosts:
            - cix1obpotd01
            - cix1obpotd02
          cluster_name: cix1obpotdcluster
  obpoam:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix1obpoam01
        dns_entries: 
          - type: cname
            name: cix1obpoam01-pca
            values: cix1obpoam01
        storage:
        - storage_name: cix1obpoam01-oracle
      - name: cix1obpoam02
        dns_entries: 
          - type: cname
            name: cix1obpoam02-pca
            values: cix1obpoam02
        storage:
        - storage_name: cix1obpoam02-oracle
    shared_storage:
        - storage_name: cix1obpoam-runtime
          hosts:
            - cix1obpoam01
            - cix1obpoam02
          cluster_name: cix1obpoamcluster
  obpoid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix1obpoid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix1obpoid01-pca
            values: cix1obpoid01
        storage:
        - storage_name: cix1obpoid01-oracle
      - name: cix1obpoid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix1obpoid02-pca
            values: cix1obpoid02
        storage:
        - storage_name: cix1obpoid02-oracle
    shared_storage:
        - storage_name: cix1obpoid-runtime
          hosts:
            - cix1obpoid01
            - cix1obpoid02
          cluster_name: cix1obpoidcluster
  obpcid:
    subnet: *sec_test_subnet
    network_security_groups: *sec_test_network_security_groups
    hosts:
      - name: cix1obpcid01
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix1obpcid01-pca
            values: cix1obpcid01
        storage:
        - storage_name: cix1obpcid01-oracle
      - name: cix1obpcid02
        operating_system: "Oracle Linux"
        operating_system_version: 8
        dns_entries: 
          - type: cname
            name: cix1obpcid02-pca
            values: cix1obpcid02
        storage:
        - storage_name: cix1obpcid02-oracle
    shared_storage:
        - storage_name: cix1obpcid-runtime
          hosts:
            - cix1obpcid01
            - cix1obpcid02
          cluster_name: cix1obpcidcluster
  obposb: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix1obposb01
        dns_entries: 
          - type: cname
            name: cix1obposb01-pca
            values: cix1obposb02
        storage:
        - storage_name: cix1obposb01-oracle
      - name: cix1obposb02
        dns_entries: 
          - type: cname
            name: cix1obposb02-pca
            values: cix1obposb02
        storage:
        - storage_name: cix1obposb02-oracle
    shared_storage:
        - storage_name: cix1obposb-runtime
          hosts:
            - cix1obposb01
            - cix1obposb02
          cluster_name: cix1obposbcluster
  obpsoa: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix1obpsoa01
        dns_entries: 
          - type: cname
            name: cix1obpsoa01-pca
            values: cix1obpsoa01
        storage:
        - storage_name: cix1obpsoa01-oracle
      - name: cix1obpsoa02
        dns_entries: 
          - type: cname
            name: cix1obpsoa02-pca
            values: cix1obpsoa02
        storage:
        - storage_name: cix1obpsoa02-oracle
    shared_storage:
        - storage_name: cix1obpsoa-runtime
          hosts:
            - cix1obpsoa01
            - cix1obpsoa02
          cluster_name: cix1obpsoacluster
  obpdoc: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix1obpdoc01
        dns_entries: 
          - type: cname
            name: cix1obpdoc01-pca
            values: cix1obpdoc01
        storage:
        - storage_name: cix1obpdoc01-oracle
      - name: cix1obpdoc02
        dns_entries: 
          - type: cname
            name: cix1obpdoc02-pca
            values: cix1obpdoc02
        storage:
        - storage_name: cix1obpdoc02-oracle
    shared_storage:
        - storage_name: cix1obpdoc-runtime
          hosts:
            - cix1obpdoc01
            - cix1obpdoc02
          cluster_name: cix1obpdoccluster
  obpobh: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix1obpobh01
        dns_entries: 
          - type: cname
            name: cix1obpobh01-pca
            values: cix1obpobh01
        storage:
        - storage_name: cix1obpobh01-oracle
      - name: cix1obpobh02
        dns_entries: 
          - type: cname
            name: cix1obpobh02-pca
            values: cix1obpobh02
        storage:
        - storage_name: cix1obpobh02-oracle
    shared_storage:
        - storage_name: cix1obpobh-runtime
          hosts:
            - cix1obpobh01
            - cix1obpobh02
          cluster_name: cix1obpobhcluster
  obpipm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix1obpipm01
        dns_entries: 
          - type: cname
            name: cix1obpipm01-pca
            values: cix1obpipm01
        storage:
        - storage_name: cix1obpipm01-oracle
      - name: cix1obpipm02
        dns_entries: 
          - type: cname
            name: cix1obpipm02-pca
            values: cix1obpipm02
        storage:
        - storage_name: cix1obpipm02-oracle
    shared_storage:
        - storage_name: cix1obpipm-runtime
          hosts:
            - cix1obpipm01
            - cix1obpipm02
          cluster_name: cix1obpipmcluster
  obpurm: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix1obpurm01
        dns_entries: 
          - type: cname
            name: cix1obpurm01-pca
            values: cix1obpurm01
        storage:
        - storage_name: cix1obpurm01-oracle
      - name: cix1obpurm02
        dns_entries: 
          - type: cname
            name: cix1obpurm02-pca
            values: cix1obpurm02
        storage:
        - storage_name: cix1obpurm02-oracle
    shared_storage:
        - storage_name: cix1obpurm-runtime
          hosts:
            - cix1obpurm01
            - cix1obpurm02
          cluster_name: cix1obpurmcluster
  obpobu: 
    subnet: *app_test_subnet
    network_security_groups: *app_test_network_security_groups
    hosts:
      - name: cix1obpobu01
        dns_entries: 
          - type: cname
            name: cix1obpobu01-pca
            values: cix1obpobu01
        storage:
        - storage_name: cix1obpobu01-oracle
      - name: cix1obpobu02
        dns_entries: 
          - type: cname
            name: cix1obpobu02-pca
            values: cix1obpobu02
        storage:
        - storage_name: cix1obpobu02-oracle
    shared_storage:
        - storage_name: cix1obpobu-runtime
          hosts:
            - cix1obpobu01
            - cix1obpobu02
          cluster_name: cix1obpobucluster
  obpodi: 
    subnet: *int_test_subnet
    network_security_groups: *int_test_network_security_groups
    hosts:
      - name: cix1obpodi01
        dns_entries: 
          - type: cname
            name: cix1obpodi01-pca
            values: cix1obpodi01
        storage:
        - storage_name: cix1obpodi01-oracle
      - name: cix1obpodi02
        dns_entries: 
          - type: cname
            name: cix1obpodi02-pca
            values: cix1obpodi02
        storage:
        - storage_name: cix1obpodi02-oracle
    shared_storage:
        - storage_name: cix1obpodi-runtime
          hosts:
            - cix1obpodi01
            - cix1obpodi02
          cluster_name: cix1obpodicluster