# Lines are commented out when the default limits are already
# equal to, or greater than, the values recommended by Oracle.
oracle              soft    nofile  262144
oracle              hard    nofile  262144
oracle              soft    nproc   20470
oracle              hard    nproc   163840
oracle              soft    stack   102400
oracle              hard    stack   327680
